#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

hash=$(ynh_string_random --length=128)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

mkdir -p $install_dir/plugins

chmod 700 $install_dir/plugins
chown $app:$app $install_dir/plugins

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="Share notes, bookmarks, and documents" --log="/var/log/$app/$app.log"

#=================================================
# SPECIFIC SETUP
#=================================================
# BUILD TURTLE
#=================================================
ynh_script_progression "Building $app..."

pushd $install_dir
    ynh_hide_warnings ynh_exec_as_app node_load_PATH npm install --unsafe-perm
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.yaml.default" --destination="$install_dir/config/config.yaml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="Listening for turtls on IP"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
